---
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http3: {}

api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: traefik_network
    exposedByDefault: false
  file:
    filename: /dynamic.yaml
    watch: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "f.mayer@foto-leistenschneider.de"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web

log:
  level: ERROR
