// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Task struct {
	ID          int64
	Description string
	Schedule    string
	Selector    string
	Command     string
	Scope       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
