# yaml-language-server: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Buld and Deploy

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

concurrency:
  group: deploy-lock
  cancel-in-progress: true

jobs:
  build:
    name: Build and push Docker image
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: https://ghcr.io
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create target directory
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/admin-panel/app/reverse-proxy/
            mkdir -p /home/admin-panel/app/vault/config
            mkdir -p /home/admin-panel/app/vault/data
            mkdir -p /home/admin-panel/app/vault/logs
      - name: Generate .env file
        run: |
          cat <<EOF > .env
          WORKOS_CLIENT_ID=${{ secrets.WORKOS_CLIENT_ID }}
          WORKOS_API_KEY=${{ secrets.WORKOS_API_KEY }}
          WORKOS_COOKIE_PASSWORD=${{ secrets.WORKOS_COOKIE_PASSWORD }}
          EOF
      - name: copy files via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ".env,docker-compose.yaml,reverse-proxy/,vault/"
          target: /home/admin-panel/app/
      - name: start compose
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/admin-panel/app
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            docker pull ghcr.io/${{ github.repository }}:latest
            docker compose down
            sleep 1
            docker compose up -d
